### PR TITLE
This is not yet a pull request: Backport the codebase to C++11

### PR DESCRIPTION
**Pull request by mbr0wn**
- Replaces chrono_literals with std::chrono::milliseconds()
- Define make_unique if not available
- Replace index_sequence with manual indexing of tuple elements
  (limits to 5 args per call on C++11)
- Replace decltype(auto) function types with C++11-compatible notation
- Replace named captures in lambdas with regular captures
- Replaced decay_t with decay<>::type

### CODE REVIEW

**Comment by mbr0wn** [comment]
I've only done some cursory testing so far. This commit still has issues that needs resolving, too, e.g., it currently defaults to C++11 instead of autodetecting. I'd like to know if you're interested in PRs like this (I've noticed there are barely no outside contributors) before I start spending too much time here.

**Comment by mbr0wn** [comment]
BTW, the replacement of `index_sequence` is pretty ugly right now. We can solve this recursively, but I just threw in something I thought would work.

...although I just realized it fails on all the tests.

**Comment by sztomi** [comment]
Yes, absolutely, and thank you very much for taking a look. This is in fact issue #33. My idea with backporting is the following: 

  * Code should be forward compatible (shouldn't be a problem with modern c++)
  * The interface should still be able to take advantage of new features via conditional compilation (for example, concept checks could be used if compiled with new standards mode and capable compiler)
  * Implementation should avoid conditional compilation as much as possible, unless there are performance implications. In this case, code should take advantage of new features via conditional compilation.
  * CI should be extended to build with older compilers as well
  * Compiler support should be documented

Of course, this is a larger chunk of work, and completing any smaller part of it is very welcome.

**Comment by sztomi** [comment]
Also, I've written some cursory guidelines earlier about contributions: http://rpclib.net/contributing/

**Comment by mbr0wn** [comment]
OK, I'll take a look at the contributing guidelines.

Note that I gave myself a 60 minute time limit to go through the code and backport it. In order to expand arbitrary numbers of elements from tuples to function args, I now believe the best way to do this in C++11 is a recursive expansion, which I couldn't come up with in that time.

**Comment by mbr0wn** [comment]
I'll split this into smaller PRs. That seems easier to discuss and get merged. I'll leave this here for reference for a bit.

**Comment by mbr0wn** [comment]
Closing in favour of #107.

**Pull request closed without merging**
