### PR TITLE
Updated doc generation and used clang-format

### PR DESCRIPTION
**Pull request by Roelli**
Hi there,

I discovered a bug in the reference that the functions are not listed in the toc.
image

So i decided to change the creation of the reference page.

I also used clang-format with the given .clang-format on client.cc and server.cc.
I did this as a preparation, because i want to add a debug message to the server as asked for in Issue #267.

Have a nice Day,
Marcel Röll

Ps: I needed to recreate the PR because i commited with the wrong user account :-)

### CODE REVIEW

**Comment by Roelli** [comment]
Why is this one failing, but if i run the failing test on my machine it is working?

**Comment by qchateau** [comment]
The test is probably missing synchronisation and is failing because the build machine is too slow. You did not do any code change right ?

**Comment by Roelli** [comment]
No, i haven't done any code changes. I once had a Problem with clang-format destroying a Macro, but not in this PR. Can we somehow re-run the tests?

**Comment by Roelli** [comment]
Looks good now.

**Comment by qchateau** [comment]
Thank you :)

**Pull request merged**
