### PR TITLE
Finalized C++11 support

### PR DESCRIPTION
**Pull request by mbr0wn**
This should satisfy the guidelines you set for providing C++11 support.

### CODE REVIEW

**Comment by mbr0wn** [comment]
I just realized there's an issue left: External callers into rpclib now need to set `RPCLIB_CXX_STANDARD`. That's stupid, obviously, so let me think about this for a sec (or do you have a suggestion?). But now it's late and I'll leave this open to see what Travis thinks.

**Comment by sztomi** [comment]
Are you interested in making sure that the implementation is also compatible with MSVC 2013? I understand if not :) In this case, I would create a cpp11 branch in this repo and ask you to rebase the pull request there; and I'll take care of MSVC.

**Comment by mbr0wn** [comment]
@sztomi MSVC 2013 (12.0) would be good to have, but I don't have a MSVC setup handy.

About the requirement to define `RPCLIB_CXX_STANDARD`: There's 2 options.

1) We make it optional to define, and C++14 becomes the default. In that case, the `#if ... #else` statements where we conditionally replace C++14 code with C++11 code need changing, but nothing else really.
2) We create an include file that is generated by CMake depending on your choice of C++ version at config time which defines `RPCLIB_CXX_STANDARD` and include it wherever required.

I *much* prefer option 1), it's less invasive, and having such a header file is too dependent on the build process and doesn't work well for other projects using this as a 3rd party lib.
Please comment on your preferred solution. Then, I suggest I fix this part, and you can take care of MSVC 2013 :smile: 

And sure, I don't mind rebasing this elsewhere. Note that I've added a test for C++11 in your travis config, so I'm feeling pretty confident at this point.

**Comment by sztomi** [comment]
Good idea, I prefer that as well. In this case, the macro can be defined in config.h. 
I've create a cpp11 branch as well.

**Comment by sztomi** [comment]
Sorry, I meant: default to C++11. I think that's what leads to the least amount of friction for any user (building the library has the highest chance of success if it works on the widest range of compilers -> so c++11 as default is better).

BTW, I don't know if there is anything in C++14 that (for the end user) makes a difference in terms of library value. Hence my comment above about questioning the retaining of C++14 implementations. If there is no user impact, the best would be just to drop C++14 code and keep the library as C++11. I toyed with the idea of adding concept checks for gcc-6 and later, and I think that's a good example of something that makes sense to be added conditionally. If the user has a capable compiler, it gives them extra value over the C++11 implementation.

**Comment by mbr0wn** [comment]
Oh, OK, I think that makes a lot of sense. However, I think this commit: https://github.com/rpclib/rpclib/pull/107/commits/4110bf52c491039d3dd8dd45c075cc4768a8a718

...is worse than the C++14 implementation (assuming you're actually using C++14, otherwise, it's probably as good as it gets).
Now, I'm not a template expert, but here's why I think your code is better: Since `call()` is defined to take an lvalue reference to a tuple, template expansion will create N functions for every bound `call()`, where N is the number of arguments.

The other place I have an `#if ... #else` is for `make_unique()`. It's possible (but that's just conjecture) that the compiler's default version of `make_unique` is somehow better than the one I wrote (it's literally copied out of Scott Meyer's book, though).
So, I'll default to C++11 but will keep the C++14 code there just in case. Worst case, someone compiles with a C++14-capable compiler and forgets to enable C++14 features, and it'll still work (yeah, I tested that).

**Comment by sztomi** [comment]
I think you are right, let's keep these conditional blocks.

As for a default standard, in the future I might even expand it to decide based on feature testing macros.

BTW I did some cursory testing with VS2013, and obviously stuff breaks (it's VS, after all...), but I think it's definitely salvageable. Biggest problem is the lack of `thread_local`, but I figured it's possible to emulate with `__declspec(thread)` and a custom pointer wrapper. That's good news because up until the latest version, even Apple Clang also lacked this feature, but it also has a similar TLS solution (`__thread`), so I think it's going to be two birds with one stone.

**Comment by mbr0wn** [comment]
I haven't actually used TLS all that much, but isn't `_thread` also what gcc uses?

**Comment by sztomi** [comment]
gcc has `__thread` as well, but it also implements `thread_local` proper (which is a C++11 feature, so any compiler claiming conformance should implement it). Apple, for the longest time disabled `thread_local` for whatever reason, despite upstream clang supporting it. The fundamental difference (which I guess escaped them up until recently) is that `thread_local` supports non-POD types with constructors and destructors. `rpclib` needs this feature for `this_handler` & friends, because they usually have destructors. `boost::thread_specific_pointer` implements this without `thread_local`.

**Comment by mbr0wn** [comment]
Ah gotcha. Really old gcc's may not have `thread_local`, so your Apple Clang hack might apply there, but gcc 4.8 has `thread_local` and going back later than that might not actually help anyone who cares.

**Comment by mbr0wn** [comment]
@sztomi What's your plan on this, and for merging the cpp11 branch? Do you want to finalize all the changes (including the MSVC changes) before it goes into dev or master?

**Comment by sztomi** [comment]
So today I had some time to play around with VS2013. It's a little bit more involved than I initially thought, so I think this can be merged as it is (since VS2013 compatibility is really not C++11 compatibility, it's VS2013 compatibility :)). I take it you don't plan to add anything else, right?

**Comment by mbr0wn** [comment]
Not right now, although I didn't do a comprehensive test using various compilers (and versions thereof). The modifications to the .travis.yml should catch it if someone adds back C++14-only features outside of conditional compilation. The only reason I could see myself adding something C++11-specific would be if I find issues with older, but still viable compilers (maybe gcc 4.8 is a good lower limit).

**Comment by sztomi** [comment]
Even though the hooks have not updated yet, the checks ran successfully already. So it's on the dev branch now. Huge thanks for this contribution, it really-really helped rpclib, because this was one of those "I really want this" but "I really don't want to do this" type of goals for the project.

**Comment by sytelus** [comment]
Hello, is C++11 is fully supported yet? We are using this library with AirSim which uses Unreal build system that doesn't support C++14 yet. Getting a C++11 only version (comparable on VS2015 Update 3) would be immensely useful to us!! If rpclib is now available that compiled with C++11 then could you let us know the branch we can get it and try it out?

**Comment by sztomi** [comment]
Hi @sytelus,

Yes, it is fully merged and can be compiled in C++11 mode with clang and gcc. You should use the latest release tag (2.0.1 currently). VS2015 was already supported (even before C++11 support was added). Did you mean to write VS2013? Unfortunately, VS2013 is rather incomplete (`thread_local` is missing for example, which is critical for rpclib), so currently that version is not supported. I do want to eventually support it, but there is no ETA. FYI, this is how C++11 mode is selected: https://travis-ci.org/rpclib/rpclib#L410 

BTW, I'm only closing feature issues if they are released. If the implementation is on the dev branch, I'll just comment here.

**Comment by sytelus** [comment]
This is great! We don't support VS2013 either so no worries. I'll try out latest release and see if we can compile with Unreal build system as well which only supports C++11.

**Comment by sztomi** [comment]
@sytelus great. If it doesn't work, I'd be interested in the details of your setup, please feel free to open a separate issue with more details.

**Pull request merged**
